# Generated by Django 2.2.5 on 2021-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_auto_20210121_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='productionHouse',
            field=models.CharField(choices=[('T-Series', 'T-Series'), ('Sony Music', 'Sony Music'), ('Zee Music Company', 'Zee Music Company'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
