# Generated by Django 2.2.5 on 2021-01-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_song_productionhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(choices=[('Classical', 'Classical'), ('Romantic', 'Romantic'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Bhajan', 'Bhajan'), ('Dance', 'Dance'), ('Disco', 'Disco'), ('Ghazal', 'Ghazal'), ('Qawwali', 'Qawwali')], default='Classical', max_length=20),
        ),
    ]
