# Generated by Django 2.2.5 on 2021-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_auto_20210121_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='singer1',
        ),
        migrations.AddField(
            model_name='song',
            name='singer2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
