# Generated by Django 2.2.5 on 2021-01-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0007_auto_20210121_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2010', '2010'), ('2005', '2005'), ('2000', '2000'), ('1995', '1995'), ('1990', '1990'), ('1985', '1985'), ('2000', '2000')], default='2021', max_length=20),
        ),
    ]
