# Generated by Django 2.2.5 on 2021-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0011_auto_20210122_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('Engligh', 'English'), ('Rajasthani', 'Rajasthani'), ('Haryanvi', 'Haryanvi'), ('Punjabi', 'Punjabi')], default='Hindi', max_length=20),
        ),
    ]
