# Generated by Django 2.2.5 on 2021-05-25 16:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0015_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='music_id',
            new_name='playlist_name',
        ),
        migrations.AddField(
            model_name='playlist',
            name='music_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
