# Generated by Django 2.2.5 on 2021-05-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0016_auto_20210525_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='music_ids',
        ),
    ]
